# Generated by Django 4.0.6 on 2023-02-14 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='授業回')),
                ('title', models.CharField(max_length=255, verbose_name='授業タイトル')),
                ('body', models.TextField(verbose_name='概要')),
            ],
            options={
                'verbose_name_plural': '授業回',
                'db_table': 'Class_times',
            },
        ),
        migrations.CreateModel(
            name='Q_format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_name', models.CharField(max_length=255, verbose_name='問題の種類')),
            ],
            options={
                'verbose_name_plural': '問題の種類',
                'db_table': 'Q_format',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('slug', models.SlugField(unique=True)),
                ('qestion', models.TextField(verbose_name='問題文')),
                ('option1', models.TextField(blank=True, null=True, verbose_name='選択肢1')),
                ('option2', models.TextField(blank=True, null=True, verbose_name='選択肢2')),
                ('option3', models.TextField(blank=True, null=True, verbose_name='選択肢3')),
                ('option4', models.TextField(blank=True, null=True, verbose_name='選択肢4')),
                ('answer', models.TextField(verbose_name='答え')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='解説')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('class_times', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='law.class_times', verbose_name='授業回')),
                ('q_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='law.q_format', verbose_name='問題形式')),
            ],
            options={
                'verbose_name_plural': '問題集',
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='User_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_question', models.IntegerField(blank=True, null=True, verbose_name='問題数')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('class_times', models.ManyToManyField(to='law.class_times', verbose_name='授業回')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ名')),
            ],
            options={
                'verbose_name_plural': 'ユーザの問題検出用データ',
                'db_table': 'User_date',
            },
        ),
        migrations.CreateModel(
            name='User_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_count', models.IntegerField(blank=True, null=True, verbose_name='問題番号')),
                ('input_answer', models.TextField(blank=True, null=True, verbose_name='入力値')),
                ('correctness', models.BooleanField(blank=True, default=False, null=True, verbose_name='正誤')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='law.question', verbose_name='問題')),
                ('user_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='law.user_date', verbose_name='問題検出用データ')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ名')),
            ],
            options={
                'verbose_name_plural': 'ユーザの解答問題',
                'db_table': 'User_question',
            },
        ),
    ]
