# Generated by Django 4.0.6 on 2023-02-14 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_question',
            name='question',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='law.question', verbose_name='問題'),
        ),
    ]
