# Generated by Django 4.0.6 on 2023-02-14 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0002_alter_user_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='class_times',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='law.class_times', verbose_name='授業回'),
        ),
    ]
