# Generated by Django 4.0.6 on 2023-02-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0004_alter_question_class_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_date',
            name='class_times',
            field=models.ManyToManyField(related_name='user_date_field', to='law.class_times', verbose_name='授業回'),
        ),
    ]
