# Generated by Django 4.0.6 on 2023-02-18 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0005_alter_user_date_class_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option4',
        ),
    ]
